# Generated by Django 2.1.7 on 2019-03-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chirp_title',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
