# Generated by Django 2.1.7 on 2019-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_shorturls_number_of_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='number_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
